"""Pantalla final de depuracion y resumen LLM de fin de partida."""

__all__ = [
    # Pantalla final de depuracion
    "DEBUG_FONT_SIZE",
    "DEBUG_LINE_HEIGHT",
    "END_SCREEN_TEXT_MARGIN",
    "END_SCREEN_COPY_BUTTON_WIDTH",
    "END_SCREEN_COPY_BUTTON_HEIGHT",
    "END_SCREEN_COPY_BUTTON_MARGIN_TOP",
    "END_SCREEN_COPY_BUTTON_MARGIN_RIGHT",
    "END_SCREEN_COPY_BUTTON_TEXT",
    "END_SCREEN_COPY_STATUS_SECONDS",
    "COLOR_COPY_BUTTON_BG",
    "COLOR_COPY_BUTTON_HOVER_BG",
    "COLOR_COPY_BUTTON_BORDER",
    "COLOR_COPY_BUTTON_TEXT",
    "COLOR_COPY_STATUS_TEXT",
    # Boton "Jugar otra vez"
    "END_SCREEN_RESTART_BUTTON_WIDTH",
    "END_SCREEN_RESTART_BUTTON_HEIGHT",
    "END_SCREEN_RESTART_BUTTON_MARGIN_TOP",
    "END_SCREEN_RESTART_BUTTON_MARGIN_RIGHT",
    "END_SCREEN_RESTART_BUTTON_TEXT",
    "COLOR_RESTART_BUTTON_BG",
    "COLOR_RESTART_BUTTON_HOVER_BG",
    # Boton "Exportar partida"
    "END_SCREEN_EXPORT_BUTTON_WIDTH",
    "END_SCREEN_EXPORT_BUTTON_HEIGHT",
    "END_SCREEN_EXPORT_BUTTON_MARGIN_TOP",
    "END_SCREEN_EXPORT_BUTTON_MARGIN_LEFT",
    "END_SCREEN_EXPORT_BUTTON_TEXT",
    "COLOR_EXPORT_BUTTON_BG",
    "COLOR_EXPORT_BUTTON_HOVER_BG",
    # Tabla de records
    "RECORDS_TABLE_MARGIN_TOP",
    "RECORDS_TABLE_ROW_HEIGHT",
    "RECORDS_TABLE_FONT_SIZE",
    "COLOR_RECORDS_HEADER",
    "COLOR_RECORDS_TEXT",
    "COLOR_RECORDS_NEW",
    # Resumen LLM de fin de partida
    "SUMMARY_PROGRESS_BAR_X",
    "SUMMARY_PROGRESS_BAR_WIDTH",
    "SUMMARY_PROGRESS_BAR_HEIGHT",
    "SUMMARY_PROGRESS_BLOCK_WIDTH",
    "SUMMARY_PROGRESS_BLOCK_GAP",
    "SUMMARY_PROGRESS_COLOR",
    "SUMMARY_PROGRESS_BG_COLOR",
    "SUMMARY_PROGRESS_LERP_FACTOR",
    "SUMMARY_FONT_SIZE",
    "SUMMARY_TEXT_COLOR",
    "SUMMARY_LABEL_COLOR",
    "SUMMARY_LINE_HEIGHT",
    "SUMMARY_MAX_LINES",
]


# ============================================================
# INTERFAZ: PANTALLA FINAL DE DEPURACION
# ============================================================
DEBUG_FONT_SIZE = 28
DEBUG_LINE_HEIGHT = 24          # Altura de cada linea en la pantalla final
END_SCREEN_TEXT_MARGIN = 40     # Margen para el wrapping de texto
END_SCREEN_COPY_BUTTON_WIDTH = 110
END_SCREEN_COPY_BUTTON_HEIGHT = 34
END_SCREEN_COPY_BUTTON_MARGIN_TOP = 16
END_SCREEN_COPY_BUTTON_MARGIN_RIGHT = 20
END_SCREEN_COPY_BUTTON_TEXT = "copiar"
END_SCREEN_COPY_STATUS_SECONDS = 3.0
COLOR_COPY_BUTTON_BG = (10, 10, 10)
COLOR_COPY_BUTTON_HOVER_BG = (35, 35, 35)
COLOR_COPY_BUTTON_BORDER = (255, 255, 255)
COLOR_COPY_BUTTON_TEXT = (255, 255, 255)
COLOR_COPY_STATUS_TEXT = (120, 120, 120)

# Boton "Jugar otra vez" (debajo de "copiar")
END_SCREEN_RESTART_BUTTON_WIDTH = 170
END_SCREEN_RESTART_BUTTON_HEIGHT = 34
END_SCREEN_RESTART_BUTTON_MARGIN_TOP = (
    END_SCREEN_COPY_BUTTON_MARGIN_TOP
    + END_SCREEN_COPY_BUTTON_HEIGHT
    + 8
)
END_SCREEN_RESTART_BUTTON_MARGIN_RIGHT = END_SCREEN_COPY_BUTTON_MARGIN_RIGHT
END_SCREEN_RESTART_BUTTON_TEXT = "Jugar otra vez"
COLOR_RESTART_BUTTON_BG = (130, 0, 0)
COLOR_RESTART_BUTTON_HOVER_BG = (180, 0, 0)

# Boton "Exportar partida" (esquina superior izquierda)
END_SCREEN_EXPORT_BUTTON_WIDTH = 220
END_SCREEN_EXPORT_BUTTON_HEIGHT = 34
END_SCREEN_EXPORT_BUTTON_MARGIN_TOP = 16
END_SCREEN_EXPORT_BUTTON_MARGIN_LEFT = 20
END_SCREEN_EXPORT_BUTTON_TEXT = "Exportar partida"
COLOR_EXPORT_BUTTON_BG = (10, 10, 10)
COLOR_EXPORT_BUTTON_HOVER_BG = (35, 35, 35)

# Tabla de records
RECORDS_TABLE_MARGIN_TOP = 8
RECORDS_TABLE_ROW_HEIGHT = 20
RECORDS_TABLE_FONT_SIZE = 18
COLOR_RECORDS_HEADER = (180, 180, 180)
COLOR_RECORDS_TEXT = (150, 150, 150)
COLOR_RECORDS_NEW = (255, 255, 0)       # ZX_YELLOW para marcador de nuevo record


# ============================================================
# INTERFAZ: RESUMEN LLM DE FIN DE PARTIDA
# ============================================================
# Barra de progreso estilo Pong (bloques horizontales que se rellenan).
SUMMARY_PROGRESS_BAR_X = 20
SUMMARY_PROGRESS_BAR_WIDTH = 760         # 800 - 2*20 margen
SUMMARY_PROGRESS_BAR_HEIGHT = 16
SUMMARY_PROGRESS_BLOCK_WIDTH = 12        # Ancho de cada bloque individual
SUMMARY_PROGRESS_BLOCK_GAP = 4           # Espacio entre bloques
SUMMARY_PROGRESS_COLOR = (255, 255, 255) # Blanco — bloques rellenos
SUMMARY_PROGRESS_BG_COLOR = (30, 30, 30) # Gris oscuro — bloques vacios
SUMMARY_PROGRESS_LERP_FACTOR = 0.08      # Suavizado del progreso visual (por frame a 60fps)

# Texto del resumen
SUMMARY_FONT_SIZE = 24
SUMMARY_TEXT_COLOR = (220, 220, 220)     # Blanco suave para el resumen
SUMMARY_LABEL_COLOR = (120, 120, 120)    # Gris para la etiqueta
SUMMARY_LINE_HEIGHT = 22                 # Altura de cada linea del resumen
SUMMARY_MAX_LINES = 8                    # Maximo de lineas visibles del resumen
